import cv2
import numpy as np
import matplotlib.pyplot as plt
img= cv2.imread('Fig0327(a)(tungsten_original).tif')
img1=cv2.imread('Fig0327(a)(tungsten_original).tif')
gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
gray_img1=cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
hist=cv2.calcHist(gray_img,[0],None,[256],[0,256])
hist1=cv2.calcHist(gray_img1,[0],None,[256],[0,256])
plt.subplot(121)
plt.title("Image1")
plt.xlabel('bins')
plt.ylabel("No of pixels")
plt.plot(hist)
plt.subplot(122)
plt.title("Image2")
plt.xlabel('bins')
plt.ylabel("No of pixels")
plt.plot(hist1)
plt.show()
gray_img_eqhist=cv2.equalizeHist(gray_img)
hist=cv2.calcHist(gray_img_eqhist,[0],None,[256],[0,256])
#localhistogram
clahe = cv2.createCLAHE(clipLimit=256,tileGridSize=(3,3))
equalized = clahe.apply(gray_img1)
hist1=cv2.calcHist(equalized,[0],None,[256],[0,256])
plt.subplot(121)
plt.plot(hist)
plt.subplot(122)
plt.plot(hist1)
plt.show()
gray_=cv2.cvtColor(gray_img_eqhist,cv2.COLOR_GRAY2RGB)
plt.imshow(gray_)
plt.show()
gray_=cv2.cvtColor(equalized,cv2.COLOR_GRAY2RGB)
plt.imshow(gray_)
plt.show()